project:
  type: book
  output-dir: docs

book:
  title: "CIRAD handbook"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - part: 10_projects.qmd
      chapters: 
        - 11_landscape.qmd
  appendices:
    - 90_meetings.qmd
    - 91_admin.qmd
    - 92_literature.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true

editor: visual
