# Meetings {.unnumbered}

## 2023

### 23/09/06 Soulemane

-   AGB mapping in ivory Coast
    -   Based on VOD (Vegetation Optical Depth) satellite product by INRAE, see @dou2023
-   Study of temporal dynamics over several periods plus future projections
-   Descriptors
    -   soil (density, texture, pH)
    -   climate (worldclim)
    -   landscape structure (% cover and isolation)
-   Construction with Camille
-   AGB part of work but also landscape dynamics and composition on the other hand

### 23/09/07 UR

-   Prévision d'une mission en début 2024 pour raconte avec Carlos Nobre de l'INP à Sao Paulo sur les question de transition de forêts tropicales humides aux savanes Cerado (échange préliminaire avec Plinio lors du sommet sur l'Amazonie)
-   Se renseigner sur le PEPR FORESTT (FAIRCARBON?)
-   Demandez à Camille puis Guillaume pour accès compte zoom unité

### 23/09/08 Camille P.

-   Réseaux parcelles (TmFO)
    -   initiative internationale
    -   Plinio S. et Jérôme C
-   PEPR FORESTT, PC Monitoring
    -   Biodiversity & structure
    -   Health
    -   Phenology
-   GeoTrees: parcelles références télédétection carbone
    -   S. Davies, O. Phillips, J. Chave, C. Piponiot (TmFO)
-   CESAB (FRB) projet groupe travail TmFO (14), 2 workshop par an à Montpellier + 1 postdoc
    -   Pb: biodiv, compo, biomasse, F exploitées, BEF, Climat ?
-   Projet NSF S. Davies réseau de réseau avec groupes travail (Mortlaité, harmonisation, botanique, ...)
-   Terri4Sol: C sol agri é forêts sud CI, Sci Po., Quantif C, scénario usages sols, restrospective
-   Expat Malaisie \> restauration & conservation
-   SOCRATES (ANR in prep.)
    -   FUNATSU Beatriz, Lilian, Arthur, Helene, Julie
    -   extremes climatiques
    -   caractéristiques aléa
    -   dynamique forêts
    -   réponse humaine

### 23/09/11 Jean-François T.

-   Coordinateur et rédacteur en chef de Bois Forêts Tropiques
-   Revue diamant depuis 1947
-   Revue du CIRAD avec Cahier de l'agriculture et REMVT
-   Rédacteur scientifique dans l'unité inclus Vincent, Jacques, et Valéry
-   En dehors participait à l'appui en télédétection, SIG et base de données
-   Formation pour doctorant et à l'étranger en écriture et valorisation scientifique
-   Projet avec ministère de l'agriculture haitiens sur la formation des cardres à l'écriture et la communnication scientifique (+ statistique vec collègue Martinique)

### 23/09/11 Jacques T.

-   2 books
-   CC \~ Agri sens large, one chapter on forest directed by Jacques. Meeting chapter leaders end of September, for a large public ("a course")
-   Forêts Humanité Compatible ?, one chapter on CC, more about a reflexive approach to bring readers to "forgotten questions"

### 23/09/11 Guillaume L.

-   socio-éco, Q gestion resources espaces à l'échelle du territoire

-   Filière et gouvernance, micro et méso-économie

-   Afrique Centrale, Cameroun, Indonésie, Montpellier depuis 5 ans

-   Étudie effet chocs sur le socio-écosystème dont beaucoup plus impactant à court terme que le CC

-   [Wilifried Pokam](https://www.researchgate.net/profile/Wilfried-Pokam-2) climatology Cameroon

### 23/09/11 Charles D.

-   Botaniste et écologue (ex IUCN)
-   Flore Afrique centrale (Gabon, Congo, Cameroun, ...)
-   Question histoire (dont évolutive) forêts
    -   Projet HIFORA M. Heuert et O. Hardy
    -   Jean mallet palynologie
-   Question forêts sub-montagnes
-   Meliacées Afriques
    -   differnce espèces, délimitation taxon, aires de distribution
    -   Déterminants écologiques (sol) et génétiques de la qualité du bois
-   OFAC (Observatoire forêts afrique centrale)
    -   Conservation biodiversité, aires protégées, compilation de données, documentation, diffusion
    -   AMCE (Autre Mesures Efficaces de Conservation) pour l'objectif 30% de zones conservées dans le monde de cadre mondiale de la biodiversité
    -   Efficacité de gestion, aires protégées et gestion participative
-   Enseignement M1 BIOGEET
-   Intéressé par climat pour les questions de distribution d'espèces avec projection futures (lien SDM)

### 23/09/12 Camille D.

-   CIRAD depuis Mars

-   Ingénieur en support informatique \~ Guillaume C.

-   Travail télédétection avec Julie ex CongoICB sur détection coupe d'arbre unique, ancien développement de méthode lasso par Julie mais succès \~60% sur image radar sentinel

-   Projet TETIS et Laurène pour cartographie des palmiers à huile

-   Travail sous python avec machine et deep learning

### 23/09/12 Cartographie AGB CI

**Soulémane T., Camille D., Bruno H.**

-   PhD Soulémane 2 service écosystémiques : biomasse (AGB) et biodiversité

-   Inventaire AGB 2016-2017

-   Variation AGB à partir de 5 drivers

    -   Paysage: carte forêts (1196, 2000, 2015) \> landscape metric software \> % couverture et variables de fragmentation mais nécessité d'utiliser un autre produit pour une meilleure résolution temporelle (forest\@risk?, MODIS Land Cover *too coarse*)

    -   Climat: WolrdClim

    -   Topography: DEM from SRTM

    -   Ahntropique: Feu MODIS 2000-2016, shp aires protégées en 3 catégories, distance ville, distance route, densité population

    -   Sol: SoilGrid (pas trop mauvais en CI)

-   Selection de variable par groupe de driver

-   Sélection de variable modèle complet avec variable sélectionnées par groupe

-   Puis test avec et sans catégorie

-   Utilisation de Random Forest

-   Résultat paysage est primordial

-   Pour la projection paassées et futures utilisation de l'indice VOD (microone \~ eau \~ biomasse) avec large échelle temporelle. Utilisation du produit brut en bande X, C, et K (L non disponible) avec la médianne annuelle rééchantillonnée à l'échelle des covariables.

-   Obj: lister produits pour voir disponibilité pour étude prospective

-   Moi: contacter INRAE Bordeaux pour produit VOD et se renseigner sur forest\@risk

-   Note: selon l'incertitude de la prédiction de l'AGB, de la projection de la surface forestière et des projections climatiques, peut être un intérèt faible pour la projection future de la dynamique de l'AGB

### 23/09/12 Jacques T.

-   Formation écologue, doctorat espèces invasive *Acacia* réunion, traits fonctionels, dispersion zoochore humain et oiseaux
-   Profil largé, généraliste, hybride avec ouverture SHS
-   Rapport arts et sciences
-   Travail sur philosophie et littérature (écriture de livres)
-   Recherche sur littérature, synthèses et animation scientifique

### 23/09/12 Guillaume C.

-   Responsable information sécurité (présentation sera programmée ultérieurement)
-   Ingénieur informaticien au CIRAD depuis 1996
-   Foresterie tropicale, exploitation sylvicole, informatique, traitement des données
-   Expertise en R et en Shiny
-   Modélisation forestière avec le développement de SELVA
-   Mais changement du peuplement au territoire
-   Compétence en SIG, raster, satelittes
-   3 PC dont 2 local 48 coeurs \~8To
-   Rféérent GitLab CIRAD pour forge institutionnelle
-   Serveur insitutionnel shiny aussi possible

### 23/09/13 Baptiste L. M2

-   Gompertz model adapted successfully from FG forest to CI agroforest (\>SI)
-   20%+ growth spontaneous vs. planted (to be kept for another article)
-   climate from Chelsa mean (median should be used) 1980-2011 (beware several periods)

### 23/09/13 Régis P.

-   Ingé agro et Eaux et Forêts
-   Forestier puis agroforestier
-   Burundi, Gabon, Cameroun
-   Inventaire, plantation, agroforesterie
-   Détaché APT Montpellier foresterie rurale tropicale
-   Retour CIRAD encadrement doctorant et travail projet
-   Foresterie et agroforesterie communautaire
-   Congo, Niger, Cameroun
-   Ex: système agroforestier à *Federbia* avec système racinaire nappe profonde et perte feuille en saison des pluies lors de la croissance maraichere (sans ombre donc), nutrition animale (déjéction pour sol) par les gousses et enrichissement en azote

### 23/09/14 Vincent F.

-   Pédologue depuis 25 ans
-   Activités d'appui et activités de recherche
-   Appui aux écologues pour la cartographie des sols notamment de Paracou et d'Afrique avec Sylvie
-   Recherches principales sur le lien sol forêts: biomasse, flore, distribution, structure, croissance..
-   Mais aussi de nombreux sujets variés:
    -   Congo Mokabi termite sol croissance forêt
    -   Sylvie modèle eau et profondeur forêts
    -   COUAC avec Bruno H.
    -   D. Bonal composition isotopique du sol avec carbone 14 pour l'âge et delta 13 pour le ration C3/C4 forêt savannes
    -   4 pour 1000
    -   Eric Nicolini sur compaction ForestTree avec Xavier
    -   RDC fertilité sol système agroforestiers
    -   Rôle WD + ontogénie sur facteur du sol limitant de la croissance des arbres (plutôt P jeune puis Ca vieux)

### 23/09/14 Bruno H.

-   100% CI
-   2 projets: Cocoa4future et Terri4sol
-   Cocoa4future, europe, multidisciplinaire, cacao culture de demain, toute la filière, 10 clusters de 10 parcelles, WP1 Biophysique, WP2 Biologie cacao, WP3 filière, Bruno et Annie, inclus travail de Baptiste (aide à l'encadrement pour publi en cours), inclus travail de Anne (besoin d'aide pour aboutir à une publi du travail de master sur allométrie H \~ D)
-   Terri4Sol, FEPEM, Influencé les politiques publiques sur la fertilité du sol. Wp1 Politiques publiques, WP2 Biophysique (Camilla) avec carte C sol, WP3 opérationnel par Nitidae
-   Dispositifs: forêts naturels (ex Tené), forêts secondaires (11 chronoséquences), forestinnov, plantations (ex CTFS), et agroforêts (15 clusters de 10 parcelles)
-   Personnes: Ruth (relation paysan arbre) , Soulémane (carto AGB Biodiv), Elogne (dyn forest), Yves Daubi (régénération naturelle des essences commerciales), Aimé (potentiel en bois des agroforêts), isac (rôle des agroforêts en carbone et biodiversité), Blandine (carbone du sol), \~Eliot (dynamique forêts secondaires), Amani (postdoc), Evans (postdoc T4C), accueil d'un béninois pendant 3 mois sur changement climatique et distribution d'espèces d'intérèts (forte intéraction à prévoir)

### 23/09/14 Sébastien Soulard - DCAF

-   DCAF: direction des comptes et des affaires financières
-   Gestion financière de projets
-   Gestionnaire de convention
-   IFD: indice marge pour financer CIRAD
-   3 outils: new C3 = saisie de temps, figaro = restitution du budget comptable, et siroco = resitution budgétaire
-   Montage de projet avec DIMS, discuté avec Sophie Beurrier

### 23/09/15 Marion C.

-   Ingénieur forestier, restauration, Amazonie
-   Travail en écologie du paysage avec Lilian, Julie et Helene
-   Restauration = technique (régé et plantation) + gouvernance (territoire, outils, intelligence collective)
-   Projet DESIRA sur la Colombie, Q stabilisation frontière agricole forêts avec réorganisation des activités pour limité l'extension du front
-   Anciennement à l'ONFI Colombie appelé ANDINA
-   Coordination d'une composante sur le design du paysage
-   Utilisation d'un outils comme élément de discussion: ForLant issue du premier projet sur Paragominas
-   Propose un outils de prospective paysagère pour des questions d'aménagement à partir d'une plateforme compilant des données cartographiques
-   Projet Ideas sur cette base avec plus d'engagement des acteurs
-   Pour le moment aucun facteur climatique dans le projet donc possiblité de recherches dans cette direction
-   Projet terrAmaz (AFD), Brazil, Colombie, Ecuador, Peru
-   Innovation et divulgation sur les territoires amazoniens
-   ingénierie du territoire, organisation des institutions, élévage, gestion forestière, financement innovant
-   \~ 20% recherche sur capitalisation des innnovations, notamment sur le financement innovant (Driss E.) et restauration
-   Correspondante du dP Amazonie à la fois géographique et thématique
-   3 axes: 1. Résilience & préservation des ressources naturelles, 2. chaînes de valeurs durables, 3. Gouvernance
-   Depuis Paragominas jusqu'à un réseau de sites avec une approche territoriale
-   15-20 insitutions (en ccroissance)
-   DR Brésil, fiches thématiques ur le dP amazonien

### 23/09/15 Manuel B.

-   SHS, éthnobotanique, doctorant laboratoire Francis Hallé
-   Recherche participatives
-   Implication des communautés dans la gestion des territoires forestiers
-   Biodiversité, Zone aires protégées
-   Implication des communautés dans les MRV
-   Au CIFOR depuis \~16 ans and Indonésie (MRV) et Éthiopie (restauration des terres dégradées avec communauté)
-   dP SALSEA en Asie du Sud Est (Philipinnes, Malaisie, Indonésie)
-   LMI (labo mixte international, IRD) sur suivi biodiversité marine Indonésie
-   A travaillé sur le monitoring par les communautés des espèces et du CC ([papier perception de l saisonnalité par les communautés](https://www.jstor.org/stable/e02d8260-d1c4-3dca-8dfb-2fb5d12a6cb5))

### 23/09/18 Direction UPR & tuteurs

-   **Contacter Laurence Le Calvez (laurence.le_calvez\@cirad.fr) pour entretien carrière et Sophie Beurrier pour rencontre (sophie.beurier\@cirad.fr) DIMS**
-   Plinio S. fait partie de Science Panel for the Amazon
-   Idiée Plinio S. est une mission début 2021 au Brésil à São Paulo pour rencontrer Carlos Nobre et commencer la construction de partenariat
-   Création de réseau :
    -   Jhan-Carlo Espinoza IRD Péruvien actuellement à Lima: Impacts de la variabilité climatique en hydrologie sur le bassin amazinien et en Amérique du Sud Tropicale (https://sites.google.com/site/jhancarloespinoza)
    -   Renan Le Roux (renan.le-roux\@inrae.fr), unité INRAE d'Avignon sur la formation aux question de traitement de données CC pour analyses territoriales, **à contacter**
    -   Vincent Durbeuil, LETG Rennes (https://perso.univ-rennes2.fr/vincent.dubreuil),
    -   Sylvain Bigot, Univ Grenoble Alpe,
    -   Nathalie Philippon, Univ Grenoble Alpe,
    -   Beatriz M. Funatsu, LETG Nantes, porteuse du projet ANR SOCRATES qui va être reproposé à l'appel d'offre du PEPRS FORESTT - axe multirisque sur l'effet des changments d'usage des terres sur les événements climatiques extrèmes
    -   GDR Point de Bascul, **essayer de participer au coloque**
    -   Jean Paul Metzger, Institute of Bioscience, University of São Paulo, **entretien semaine prochaine**, séminaire UR fin 3/24, 1 axe environnement forêt et CC
    -   Vincent Blanfort, CIRAD, animateur CC pour le CTS CIRAD
    -   Aude Valade, CIRAD Eco&Sol, Provision of ecosystem services by tropical plantations faced with climate change
-   Rédiger le plan de compagnonage (**demander modèle Julie**)
-   Stratégie UPR:
    -   Arthur P. à Santarèm sur la gestion forestière communautaire dans le cadre d'un projet FFEM
    -   Géraldine Derroire à Brasilia
    -   Isabelle Tritsch sur les forêts sèches du Brésil
    -   Lilian, Marion, Julie sur TerrAmaz
    -   Marie Ange Ngo Bieng, FFEM, Guatemala & Santarém
    -   Beatriz Bellón, postdoc Julie, exemple éologie pysage oiseaux
    -   **Se placer sur terrAmaz2 pour questions CC (!semaines à venirs)**, à discuter avec Marie Gabrielle Piketty (UMR SENS) et voir projet terrAmaz (Lilian, Marion, Julie)
-   Mes questions (prospectif):
    -   Déforestation au Cerrado \> dynamique forêts humide / savannes Cerrado
    -   Question d'échelles, parcelle (mécaniste) \> territoire (UPR) \> région (projections), voir changement d'échelle avec Camille P.
    -   À construire avec les intéractions mais aussi prévoir de s"adapter selon l'appel à financement et les questions dans collaborations (bien que ce serait bien qu'avec 4 chercheurs l'UPR porte ses propres projets au Brésil)
-   **Priorités: formation & discussion partenaires recherches potentiels et questions de recherche (faire le point début 2024)**
-   Financement mission international via plan compagnonage (1 mission mais peut être mixte Isabelle Tritsch à Fortaleza, Carlos Nobre à Sao Paulo avec Plinio, et terrAmaz Cotriguacu avec Julie et Lilian (Mars))
-   Financement petite moibilité métropole avec budget chercheur CIRAD (\~2400€) à voir avec Marie-Jo lors de mise en place de mission (ex. GDR ou Avignon)
-   Possibilité de financement de postdoc (plus facile) ou thèse (moins facile) au travers des appels du CNES : candidat à envoyer à l'oral, 2 pages de projet, 2 ans en télédétection, demander à Julie
-   Développé le projet "AFRICLIM2", intérèt de Julie et autres

### 23/09/19 Clarisse V.

-   Formation transformation bois ENSTIB Epinal
-   Guyane, Réunion, Congo transformation bois
-   2021 M2 Géomatique alternance UPR F&S puis recrutement
-   Poste transversal IR appuie recherche
-   Besoin géomatique, analyse spatiale, télédétection, données satellitaires
-   Réalisation &!/ou accompagnement
-   60% PUDT en appui géomatique
-   Outils R, Qgis, \~googleearthengine

### 23/09/19 Frédéric M.

-   PhD Climat + Enquete + Présence seule depuis 1970 dans la région soudano-sahélienne
-   Analyse de processus ponctuels marqués
-   Inclusion possible dans le comité de thèse pour voir lien avec dynamique du climat
-   Vivien Rossi se pose aussi des question sur les échelles multiples, depuis une vision locale mécaliste à un agrandissement probabiliste

### 23/09/19 Direction ES

-   Réseau intra-CIRAD car thématique majeur mais sur peu de chercheurs dispersés
-   Y inclus, TETIS, Aude Valade, et Rémi Prudhomme

### Ideas on the fly

-   TmFO (or first Guyafor) + TROLL + LoggingLab + soil + climate
-   Build trajectory and calibrate on observations from ground and teledetection
-   Local & regional projection of CC & logging

### 23/09/19 Géraldine D.

-   Envisage expat Brasilia l'EMBRAPA
-   Q exploitation TmFO Amazonie
-   Q restauration passive et active sur trajectoire alternative d'ecosystème (possible lien point de bascule)
-   Contact Lucas Mazzei de l'EMBRAPA lors passage CESAB

### 29/09/20 Livre Forêt Humain

-   Les forêts et les humains sont ils compatibles ?
-   Pas un livre sceintifique mais un essai de pensée par des scientifiques
-   Contributions courte (3-4 pages) avec peu de références

1.  Origines écologiques, culturelles, et sociétales d'une présumé incompatibilité
    1.  Forêt permanente ?
    2.  Regard occidental exporté
    3.  Histoire de l'évolution de la foresterie
2.  Forêts et territoires
    1.  Penser forêts et territoires
    2.  S'appuyer sur la communauté - Faune
    3.  Gestion communautaire - Ligneux
    4.  Populationl locale et cartographie mentale
    5.  "Mise en jeu" des forêts
3.  Changements globaux : regarder autrement les forêts
    1.  Regards forêts en recomposition (+)
    2.  Préserver forêts / droits des occupants
    3.  Aires protégées remises en question
    4.  Feux ? (+)
    5.  Forêts secondaires et émergentes
    6.  Déforestion importée et déforestation durable
4.  Synthèse réfléxive sur le rapport entre sciences et forêts
    1.  Incertitudes (+)
    2.  Étrangeté
    3.  Arbres en tant qu'acteurs ?
    4.  Causes de la déforestation et de la dégradation
    5.  Forêts entre sciences et sociétés, penser la science entre forêts et sociétés

### 23/09/20 ODM

-   Intranet \> Acès direct \> tout formulaire \> DCAF \> ODM NDF
-   Dépt C = ES \> Structure
-   Code projet foncitonnement chercheur = A01T004
-   2400€/agent mais pro rata
-   Frais à rembourser: hébergement, repas (max 20.2), transport (i.e. métro)
-   Frais engagé: ex train
-   Envoi Marie-Jo et Julie C.
-   Puis post mission NDF + pdf justificatifs

### 23/09/20 Carto Biomasse CI Soulémane

-   Forest cover
    -   LandSat (from GoogleEarthEngine or Planetary currently used by Camille) \> Composite (\>1) \> NDVI \> Random Forest \> Forest Cover
    -   Land cover 1992:Present from CDS to evaluate with sensitivity and precision <https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-land-cover?tab=overview>
-   Biomass
    -   Drop VOD because not retained by model because too coarse
    -   MODIS indices of vegetation (NDVI, EVI, LAI, FPAR) 2013-2017, that could be replaced by CDS similar products for longer periods
    -   Climate from WorldClim2 mean of 1970-2000
    -   Soil (origin?)
    -   Landscape structure from forest cover
-   To share
    -   getEra & singularity image
    -   rcontroll example of CDS data
    -   netcdf4 package
    -   CDS link to products similar to MODIS indices
    -   AfriClim article and data access
-   To ask
    -   Forge for Camille's code
    -   CI forest cover maps
-   Idea on the fly: build a local data dictionary with origin download all metadata (ex CDS) tracked changed on GitHub to ease data stockage across computers and working

### 23/09/20 Plinio S.

-   DU depuis 2015
-   Thèse Paris 6 Guyane française régénération du palmier à la piste de Saint Élie de 85 à 89
-   Avant expatrié 9 ans en Indonésie et 9 ans au Brésil
-   Impact exploitation forestière sur dispositif STREC du CIRAD à Bornéo
-   Mise en avant du rôle de l'intensité
-   CIFOR mise en place d'un dispositif à intensitées fixées en bloc de 100 ha
-   Belem projet EU sur la foresterie de s zones agraires obligé par le code forestier et projet FFEM sur la valorisation des forêts communautaire de petits paysans
-   2010 retour à Montpellier et construction du réseau TmFO actuellement projet CESAB (**mail Camille idée rcontroll + logginglab + climate forcing + TmFO**)
-   Depuis DU encadrement Camille, Andes en Indonésie et démarrage futur d'un PhD sur STREC

### 23/09/21 Webinaire PC1 REGE-ADAPT - PEPR FORESTT

-   Task 1 Ecology - Lisa Laurent, Isabelle Maréchaux, Xavier Morin
-   @mcdowell2020
-   Regeneration following different disturbances: harvest, salvage, afforestation (@schmitt2020, ALT)
-   Plantation / Natural regeneration
-   Nature Contribution to People NCP (wood, beauty, watershed...)
-   Task 1 : Regeneration Ecology : 1A-Monitor, 1B-Experiment, 1C-Model
-   1C Model @hanbury-brown2022, @könig2022
-   2A: Managing regeneration at the stand scale with question of diversity and species adaptation. **Beware**, technical implementation questions. Sylvicultural practices in FG with LoggingLab and rcontroll climate forcing?
-   2B Management regeneration at the landscape scale. Links with living labs from PC4
-   2C Regeneration pathway effect on biodiveristy / NCP. TROLL!
-   **Codesign with Expression d'Intéret EI (need to network to build EI, ALT, TROLL, TmFO?) \> Upscaling for 2B? linking with territory and interdisciplinary with other colleagues working on societies.**
-   EI before end of October
-   Discuss with Camilla and Isabelle M.?
-   Total budget: 4M€
-   Benjamin Brachi: living lab Chantilly genetic diversity in regeneration
-   **Find back article on why focusing on CC in multirisk**
-   Webinaire by task after (**take care to 1C, 2A, 2B and 2C**)
-   **Push behind ALT with TmFO? To discuss with Jérôme and Isabelle, and Camilla? Link to PEPR.**
-   **Follow up on Julien's PhD about Climate effect on *Dicorynia guianensis*?**
-   **Have a look to Marta Benito Garzon's work on forest dynamics on climate change close to my questions.** See @leites2023.
-   Beware about PEPR Fair Carbon with experiment on drought link to carbon dynamics in ecosystem
-   PEPR is not financing foreign scientist
-   Welcoming students from south countries
-   EI is tool and data to help the project (not the other way around)

### 23/09/21 Bruno L.

-   2001 CIRAD GREEN (maintenant SENS)
-   Thèse avec Jacque Weber sur la construction paysanne des paysages à Madagascar
-   Costa Rica 6 ans, 7 ans Indonésie, 7 ans Pérou
-   Recherche dispersée
-   Adaptation au CC des socio-écosystèmes ave les services écosystémiques
-   Postulat: besoin de changer les relations avec la nature en travaillant les relation Homme-Nature & Homme-Homme
-   Réseau TARA avec S. Lavorel et M. Kohlof sur \~30 cas d'étude d'adaptation

### 23/09/21 Phillipe V.

-   Généticien quantitatif sur la sélection et l'amélioration des plantations au CTFT, notamment eucalyptus et pin
-   Congo, Nogent-sur-Marne, Partout (DU plantation forêt), COngo, Gabon (Responsable SWM)
-   Q: prédiction saisonalité est gabon

### 23/09/21 Julie B.

-   Deux axes: télédec et écologie paysage
-   Télédec Radar & Optique sur impact dégradation forestière avec depp learning notamment pour petit impact de l'exploitation conventionnelle
-   Gros jeu de données à exploiter sur tout le Mato Grosso avec tout impact de l'exploitation légal et illégal en shp avec possibilité de demander au CEMA les volumes déclarés et intérèt du JRC
-   Écologie du paysage sur les services économique et la connectivité avec des données animales, possibilité intéraction SSDM, ex SWM connectivité animaux
-   Travail avec AMAP (P. Couteron), TETIS, Univ. REnnes, CESBIO
-   À faire :
    -   ~~Envoyer SSDM~~
    -   ~~Partager EL paper and Rmds~~
    -   ~~Demander à Guillaume d'envoyer son CV~~
    -   ~~Regarder ANR SOCRATES~~
    -   ~~Contacter Beatrice Funatsu~~
    -   Discuter avec Beatriz
    -   Préparer le plan de compagnonage rapidement possiblement février mars 24 (Possiblement Carlos Nobre Sao Paulo, Isabelle T. à Fortaleza, Arthur à Santarem, et Julie & Lilian pour TerrAmaz)
    -   Apprendre le portugais (contacter service formation)
    -   ~~Rencontrer Damien Arvor lors de sa visite d'unité lundi prochain~~
    -   Discuter d'un éventuel projet TOSCA avec Julie

### 23/09/22 Fabrice B.

-   Recruté 2009 en tant qu'informaticien pour la gestion des données
-   WEB, BD logiciel
-   BD forêt Paracou M'Baiki
-   Site web et communication (outil easy publish)
-   Groupe travails patrimoine numérique, dataverse, IDG, FAIR

### 23/09/26 Stages Régé

*Mélaine A., JB Durand, Nico Barbier, Greg Vincent, Julien Bonnier*

-   Stage 1: \~ Benjamin Lagrange qui est pris en CDD 1er Oct pour 3 mois et possiblement rallonge sur l'identification des phénophases de Dico & Sympho à l'aide de la télédec dans PhenObs
-   Stage 2: modélo multisource phéno markov caché
-   Données de Thomas sur patch de Xm de rayons +/- loin des trouées avec comptage des espèces commerciales
-   PhenObs = 1500 inds sur \~ 3 cycles annuels

### 23/09/27 Beatriz Bellón

-   PostDoc 2 ans CNES, porteuse projet accueillie par Julie
-   Axe 1 : Tajectoire des paysages amazoniens au Brésil
    -   Occupation des terres à partir de **MapBiomass** depuis Landsat au Brésil de 85 à ajd à 30m
    -   TMF (prod JRC) état forêts à 30m depuis 1980, Clément Bourgoin
    -   =\> Land Use Cover Chance (LUCC) with different steps and dynamics (eq diff?, SEM?)
-   Axe 2 : Effet de la trajectoire du paysage sur la connectivité écologique
    -   GBIF, ebirds, 2019 btw forest and generalist
    -   SDM \> habitat suitability \> landscape resistance \> ecological connectivity
    -   Use of more sophisticated teledec products e.g. var NDVI from Sentinel2 & GEDI
-   Indices of teledec on IDB: https://www.indexdatabase.de/

### 23/09/28 Lilian Blanc

-   \~20 ans, CIRAD, ECOFOG Paracou
-   D'abord GF Dyn forest, Dyn C, impact logging, Dyn Biodiv
-   Puis Belem, territoires, Paragominas, dP Amazonie
-   Très dégradé, feux, pas de gestion forestière
-   Thèse C. Bourgouin sur dégradation forestière
-   =\> Projet TerrAmaz pour indicateurs sur les forêts autres que couvert/déforestation et intéraction forêts agriculture
-   **Q lien fue paysage à développer**
-   Q sur la déf unité paysage
-   indices sur les services écosystèmiques: sol (pb érosion), carbon (Q écnomique), modification local du climat (obs CHIRPS historique)
-   But ex Paragominas de certification du territoire pour attirer investisseur, donc besoin de caution scientifique, donc regard intéressant des acteurs qui cherche une rigueur importante
-   Besoin d'indicateurs simples, compréhensibles, temporels, gratuits et fiables (-incertitude)
-   **Prévoir discussion avec Lilian et Guido sur indicateurs climatiques TerrAmaz**
-   Pour question de restauration utilisation de ForLand par l'ONFI pour tester des scénarios d'évolution du couvert forestier
-   **Possibilité de travailler sur lien dynamique du couvert et projections climatiques?**

### 23/09/28 Aude Valade

-   ORCHIDEE \> intégration communauté
-   Encadrement thèse Dakar sur adaptation ORCHIDEE savanes sahéliennes, travail avec données multiples (tour à flux, radar racinaire, dynamique nappe...)
-   Quesiton d'hétérogénéité dans ORCHIDEE
-   [Benjamin Sultan](https://theconversation.com/profiles/benjamin-sultan-1383400) chercheur IRD sur question de Climat
-   Travail aussi sur cycle carbone dans filière bois
-   Travail aussi en RSE avec projet RESPIRE sur l'effet du changement climatique sur nos conditions de vie
-   Pour liens paysage déforestion et modèles CC regarder LUMIP sur comparaison modèle changement d'usage des sols
-   Pour événements extrèmes, prendre contact avec Émeline Chaste (à deposer une EI au PC Multirisque du PC du PEPR FORESTT) avec lien feu et etrèmes climatiques

### 23/10/01 Isabelle Maréchaux

-   Send link to online document
-   Send link to code differences with Isabelle version
-   Schedule an article led by Isabelle on TROLL v4 model in Geoscientific Model Development in the New model section
-   Schedule a companion paper in GMD in the Evulation model section
    -   Eventually led by me
    -   Including Paracou, 1 Santarem site (maybe the most different), and eventually Caixuana for throughfall exclusion experiment (TFE) inclusion
    -   Using the phenology approach chapter
    -   Including Climate forcing of each site with the eddy flux when available
    -   Including species community to gather
    -   Including soil data to obtain/ask
    -   Including the TFE experiment
-   Schedule a postdoc offer for a subject on the role of biodiviersity in ecosystem resilience to climate change building up on my climate forcing experiment
-   Discuss the possible link between logging, forest dynamics with TROLL and eventually climate forcing with the whole TmFO dataset. To be discussed with Camille Piponiot and Géraldine Derroire
-   Discuss with Jérôme the possiblity of regionalisation but asking the question behind
-   A meeting with Jérôme is to be scheduled
-   Idea following @rödig2017: similar approach for Amazon simulation of diversity validating with ATDN?

### 23/10/03 Rémi Prudhomme

-   Ne travail pas sur l'adaptation mais sur les stratégies d'aténuation du CC par diminution des émissions GES
-   Approche large échelle nationale ou globale
-   Impact de l'agriculture sur l'environnement par GES/C (méthane, N20, Azote, ...), biodiversité, service écosystémiques
-   Approche par modélisation soit des flux de biomasse, soit avec un modèle d'équilibre économique
-   Intérèt pour tipping point & permance/risque des stocks de C forestier (cf papier économie et climat sur tipping point)
-   Principe précaution, politique optimale, ...
-   Contact possible Phillipe Roudier

### 23/10/03 CodES

-   Aurélie Botta (dir SENS), thème thèse similaire à projet, travaux LBDA à regarder
-   Nouveaux arrivants
    -   Andrea Cinique (Cired) Climat \~ Économie
    -   Gabriela Demarchi ingénieure forestières brésilienne, notamment économie des mesures contractuelles pour protéger la forêt brésilienne

### 23/10/03 Nathalie Philippon

-   Travail plutôt à large échelle sur des grandes entités et plutôt en Afrique
-   Intérèt pour caractériser les forêts d'Amazonie sur base de leur fonctionnement en lien avec le climat (similaire Afrique Centrale, À discuter avec Valéry)
-   Particulièrement lien greenness (ou autre) avec rayonnement sur base de classifiction
-   L'idée est que les nuages sont centraux car ils modulent (1) l'eau par les précipitations, et (2) la lumière par le rayonnmenent et comment ils affectent l'évapotranspiration
-   Exemple aussi de travaux sur des incursions d'air chaud ultra sec du Sahara sur des stations météo qui peut influencer les feux et la croissance des arbres (quid de l'Amazonie)
-   Pour la question au niveau du territoire du lien entre dynamique du couvert et cycle de l'eau se référer aux travaux de Filares et al. (à demander). Ils ont étudié l'effet multiéchelle (spatial et temporel car atttention temporellement aux effets transitoires) de la perte de ouvert forestier, avec par exemple une augmentation de précipitation les premières années après la perte de couvert (effet transitoire) car la convexion est attiré par la création de gradient de température et d'énergie créé par la perte de couvert

### 23/10/04 Coloque points de bascule

-   **Tim Lenton**
-   Boulton et al. (2022) Nature Climate Change: AR(1) of VOD and Kendall Tau to assess tipping point proximity
-   Armstrong McKay et al. (2022) Science: Review tipping points and current level of risk depending on temperature rise
-   Lenton et al. (2019) Nature: Connections between tipping points, e.g. Altantic Circulation Reduction \> ZIC movements \> Amazon die-back
-   Lenton et al. (2020) OECD Report: 2.5°C + tipping point = very different scenario
-   Rocha et al. (2020) Science: tipping points interactions across scales
-   Opening on social, energy, economy, and politic positive tipping point for decarbonization =\> Lenton et al. (2022) Global Sustainability
-   Interesting reaction on geo-engineering question: injecting particles in atmosphere to play with irradiance seems more risky than effective and should be explore but not implementer, on the other hand more largely considering working with biosphere (forest etc) seems more promising
-   **Didier Swingedow** (UMR EPOC, Bordeaux)
-   Valesco et al. (2021), Ureta et al. (2022) Communication Biology: GCM with/without ice melting -\> SDM in Mexic -\> Biodiversity loss
-   But beware limits of the study
-   Interest for JSDM & Climate Projections
-   **Peter Ashwin** (U. Exeter)
-   Maths of tipping points, bifurcations, and instabilities
-   Beware, median and means are non sense in tipping systems
-   **Niklas Boers** (TÜM)
-   Boundaries are less elastic before tipping point causing a slowing down of the system in an Orstein-Unlenbeck process allowing to detect them thanks to auto-regressive processes with "Early Warning Signs" (EWS)
-   Anyhow, this does not inform how long do we have to deal with it after the threshold, a huge window of response depending on how much you go aboce the threshold (e.g. slow tipping of ice melting)
-   Greenland melting slow down the AMOC with a local decrease in salinity and temperature that in turn disturb the ZIC movements and can cascade on the Amazon dieback
-   Beware false positive due to AR noise, that might be avoided using GLS accounting for it
-   Beware gaps when measuring AR
-   AMOC collapse results in massive decrease of precipitation in the tropics
-   Amazon recovery analyzed with VOD and AR(1) show a slowing down of the recovery rate
-   Beware the multisensor datasets inducing biasses because of merging
-   Beware NDVI and EVI saturation with high AGB that makes is useless in TMF
-   Tree cover \~ MAP is a good example of S curve of bistable state ecosystem ( but does it account for soil and degradation?)
-   Boulton Nature Climate Change 2022, AR for VOD product classified with MAP and distance to human land use
-   Boers 2017 \> moisture recycling in the amazon, with deforestation in the east implying a risk to break the chain
-   Bochow Science Advances 2025 shows increase in dry season length and decrease in soil moisture
-   Climate models appears to stable and need for tipping points
-   **Vasilis Dakos** (ISEM, Montpellier, Ecology)
-   Define tipping point as abrupt, unexpected, substantial, and often difficult to come back (hysteresis)
-   Definition of tipping point in van Nees TREE 2016 (but numerous exists)
-   Dakos & Kefi 2022 ERL \> Ecological Resilience
-   Catastrophe theory applied in Ecology
-   Tipping point slower recovery, more variance, more autocorrelation
-   Boettiger 2023: classification of alternative states
-   Dakos 2013 Philosophical Transaction B Royal Society
-   Dakos 2012 earlywarnings R package
-   Dakos 0223 EGU sphere review of example theory applied on data
-   Liu 2019 Nature Climate Change
-   Fozieri & Dakos Nature 2022, beware NDVI in tropics
-   We can use the approach on models outcome (TROLL?, CC sims?)
-   Need long term and/or high frequency data to see small changes (Paracou?)
-   **Jérôme Chave**
-   AGB Amazon Xu 2021 Science Advances
-   Cycles H2O Amazon Zemp 2017 Nature Communications
-   Wongchuiq 2022 International Journal of Climatology
-   Araujo (in press) PNAS \> spatial analysis of drought or chain reaction tipping points
-   Saatchi 2013 PNAS: link drought \~ mortality
-   Fleischman 2021 Remote Sensing: classification of Amazonia with inundation (vs Climate N. Phillipon?)
-   Tao 2022 PNAS \> Radar Drought \> AR(1) \> Tipping Point
-   Beware, Tao (in press) Nature Climate Change show issue with VODCA series use by Boers with sensor changes and flood events \> contradict AR(1) Noulton et al. (2022) Nature Climate Change
-   Need to further include extreme events in this thinking because they could tip of tipping points not included in this mean answers
-   **Idea on the go** to organize my projects
-   A\) Support: e.g. RegionalClimate (G. Vieilledent et al.)
-   B\) Development: TerrAmaz2, SOCRATES, TmFO, FORESTT
-   C\) Fundamental: tipping points in Amazonia, Amazon dieback, Nobre Team, TROLL-biodiv (ERC for high uncertainty and contradictory messages that calls for transdisciplinary approaches, ecology and teledetection of forests being oversimplified in most talks)

### 23/10/09 Guillaume Salzet

-   FPCA for climate decomposition (spatial, temporal, etc) using the mfpca R pacakge
-   LVIS NASA campaign over French Guiana to calibrate GEDI

### 23/10/09 Isabelle Tritsch

-   Catinga, NordEste, Forêt sèche
-   Projet gestion de l'eau termine en 2023
-   Vision intégrée de la gestion des ressources naturelles
-   Expatrié au FUNSEM \> laboratoire de météorologie qui monitore la séchéresse et travail sur la prévision du risque pour les forêts sèches mais aussi amazoniennes avec notamment l'indice monitor da sec en cours d'appropriation par les états amazoniens
-   Isabelle est géographe plus spécialisée des sciences participatives, avec un ici un travail multi-échelle d'un micro-bassin en tant que territoire pilote, en passant par une commune, avant d'arriver à la gestion de l'état

### 23/10/10 Beatriz Funatsu

-   Physicienne Atmosphere et climat
-   Travail avec mathématicien sur modèle d'ODE pour la dynamique forestière à Paracou
-   Papier point de bascule face aux évenements extremes
-   Extremes caractérisés par fréquence, intensité, persistence, et étendue spatiale
-   Typiquement extreme sécheresse, pluies et températures
-   Travail beaucoup sur le cylce de l'eau avec données satelittes, [TerraClimate](https://www.climatologylab.org/terraclimate.html) , Réanalyses, à une échelle de 4-5 kms.
-   Expertise Climat mais Forêt
-   Échelle globale et régionale
-   Intérèt pour les feux, article climat \~ proba feu
-   Effet cascade et advection vapeur d'eau dans articles de Zemp inclus dans les modèles ODE
-   Question échelle territoire pour le climat \> À explorer car effet potentiellemet similaire aux îlots de chaleur urbain \> mais nécesséité de regarder à échelle large puis focus ou peut être en comparatif local \> ou alors approche de microclimatologie mais couteux en capteur sur des séries longues
-   Peut être contacter Damien Arvor (télédec) et Vincent Dubreuil (ilot chaleur)
-   Articles water vapour recycling : @zemp2014, @zemp2017, @cantin2021
-   Article feu : @silvajunior2022
-   Articles événements extremes : @funatsu2021

### 23/10/16 Vincent Blanfort

-   AgroÉcologue des paturages
-   Thématique carbone dans l'élevage
-   ECOFOG: tour à flux paturage, chronoséquence, et stock de carbone, bilan de carbone, analyse de cycle de vie
-   Outils ACCT exporté à Paragominas
-   Charg" mission CC CIRAD et coanimateur CST CC
-   Alimentation réseaux G20 et GIEC
-   Note positionnement CIRAD (à lire)
-   Constitution d'un groupe climat interinstitut pour plus de poisd à l'international
-   COOP Brésil 2 ans

### 23/10/18 Émeline Chaste (PostDoc Eco&Sol)

-   Study disturbance in ORCHIDEE including cyclones, drought-hydraulic, pests, and fire (SpitFire module) but mainly on temperate and boreal forests
-   Want to study them jointly for multirisks and to better develop them in the tropics
-   PEPR PC2 also include CAPSIS

### 23/10/19 Helene Dessard

-   Restauration des paysages forestiers
-   Approche sur l'intelligence collective et les outils de coordination pour aligner les objectifs et décisions collectivement (ex COMOD)
-   Expertise processus ForLand
-   Scénarios participatifs
-   Très intéressée projet type SOCRATES avec un triangle Climat - Dyn forêt - Décision/Gouvernance centré sur la question des événements extrèmes et des feux
-   Intérèt pour modélisaiton plus large échelle voir multiple dans de tel projet (TROLL, ORCHIDEE)

### 24/10/19 Marie Ange Ngo Bieng

-   Cursus tempéré - écologie forestière
-   Distribution spatiale, statistiques appliquées, modèles de structure forestière
-   Question coexistence des espèces, lumière, pratiques sylvicoles
-   Recrutée au CIRAD en 2007 sur agroforêts et modèles de distribution spatiale canopée
-   F&S depuis 6 ans sur question écologie intéractions des arbres
-   HDR 1/23 sur la dynamique de récupéraction des écosystèmes forestiers
-   beaucoup sur la dynamique des forêts secondaires
-   beaucoup sur les facteurs anthropiques de la dynamique des forêts secondaires
-   Concessions forestières au Guatemala
-   Pression El Nino / La Nina sur Guatemala et feux néotropicaux
-   Projet jeu fête de la science ClimateRush
-   Contact Jhan-Carlo Espinoza en me mettant dans la boucle
-   Projet FFEM Gestion Forestière Communautaire

### 24/11/09 Jean Paul Metzger

-   Service écosystémique de régulation du climat: C storage, cooling, water dynamics (etp)
-   Nouveau institut dans L'université de Sao Paulo avec le FAPESP: Centre Étude de l'Amazonie (Centro de Estudos da Amazônia Sustentável) avec Paulo Artaxo
-   Volonté travail Mata Atlantica
-   Mise en place IRC avec CNRS, contact Jérôme Chave
-   Mission Février avec Joannès Guillemot de Eco&Sol

### 24/11/17 Bruno Pinho AMAP

-   Importance of landscape scale studies Lehore Farig e.g. 2017
-   FragSAD dataset about fragmentation
-   Match JP Metzger paper
-   40% threshold of forest cover
-   **Demander les diapos**

### 24/11/17 Julie B, Lilian B

-   Link landscape structure and trajectories to climate dynamics + projections
-   Looked at mean climate, climate extremes, and progressively to fires risk
-   Worked on the Amazon deforestation front with Beatriz B. trajectories
-   Julie can produce several metrics of landscape structure
-   To be linked with forest local functioning based on remote products (maybe linked to trajectories)
-   Need to define the weather product to be used (satellite, gauges, re analyses...) depending on temporal and spatial scale and avoiding smoothing of the anomalies we are looking for
-   Julie super interested by link structure and dynamic of landscape to climate evolution
