# Projects {.unnumbered}

## Climate

*downscaling, characterisation, definition, multi-scale, ...*

### Tool for downscaling (+)

*G. Vieilledent, T. Arsouze, Achille Mauri*

-   Problem: a lot of local projection rely on downscales GCM projections with very low spatial resolution on known baseline (e.g. CHELSA, WolrdClim, ...)
-   Idea: a tool to derive projections from CORDEX regionalisation experiments [@platts2014] on a defined baseline
-   Study area: French Guiana, New Caledonia, Ivory Coast. Opportunistic following G. Vieilledent and B. Hérault needs but also different hypothesis. New Caledonia as an important topographic variation. Ivory Coast as an important climatic variations. On the opposite French Guiana is mainly lowland and homogeneous as a control.
-   Validation: (1) explore the possibility to do a projection on observed year (e.g. 2005\>2020) even if the differences between scenarii (RCP or SSP) will not be significant, and (2) explore the difference on ecology for instance with forest climatic extent with this product versus classical products.

### *Amazon forests climatic typology (-)*

*N. Phillipon, V. Gond?*

Characterization of different forest types in relation to climate/season (radiation, cloud, precipitation, evapotranspiration) and ecosystem dynamics (greenness, GPP, etc., N. Philippon, V. Gond, ...). Similarly to @philippon2019. Beware the importance of hydrology and inundation in Amazonia [@fleischmann2022; @fassoni-andrade2021].

## Amazon

*tipping point, die-back, degradation, deforestation, large-scale, theory, ecology, dynamcis*

### Amazonian Landscape in Transition (+)

*I. Maréchaux, J. Chave, F. Fischer, postdoc Montpellier, postdoc Toulouse*

[My webpage on the project](https://main–altpages.netlify.app/)

1.  TROLL V4 description (*IM*)
2.  TROLL V4 validation Paracou, Santarèm, Caxiuanã (*SS*)
3.  Role of biodiversity in response to climate change locally (*PM*)
4.  Forest response to CC projected to the scale of French Guiana (*PT*)

### *Regeneration of exploited Amazonian forests in the face of climate change (=)*

*I Maréchaux, G Derroire, M Aubry-Kientz, C Piponiot-Laroche, et al.*

Simulation of forest response to logging in relation to climate at the scale of TmFO South America (C. Piponiot, G. Derroire, CESAB, EI PEPR FORESTT - PC RegeAdapt?, link with M. Aubry-Kientz Regeneration project?)

submitted as an [EI to PEPR FORESTT PC2 REGE-ADAPT](https://docs.google.com/document/d/12GChS5BLZc-oB2idSKHaNzPICkKILpR2CXLMuNEli8A/edit?usp=sharing), in preparation for an FSPI project

### *Paracou dynamics under climate change across scales (-)*

*B. Hérault*

-   Growth ind, sp, ecosyst in time using TreeGrowth results
-   Link with climate from ERA5-Land and the EddyFlux
-   Work with climate and growth anomalies
-   Link with ecosystem functioning using Eddy fluxes and remote sensing products (SIF, VOD, LAI, NDVI, ...)
-   Explore tipping points with AR(1)

### *Individual-based projections of the Amazon (-)*

Multi-scale modelling of Amazonia with TROLL following @rödig2017, @rödig2018, & @rödig2019 with (1) response to climate change and/or (2) simulation of diversity with validation using ATDN?

### *The Amazon tipping point* *(-)*

-   Similar approaches to @dakos2022 and @boulton2022 but see Tao et al. (in press) Nature Climate Change in response
-   Discuss with J. Betbeder possible products in Amazonia for such studies and with multiple entry point for multiple arguments

### *Extreme events (?)*

*B. Funatsu, Emeline Chaste, PEPR FORESTT - PC2 Multirisques*

Characterization and effects of extreme climatic events on tropical forest dynamics (SOCRATES)

## Landscape

*territory, remote sensing, management, local actors*

### *Landscape and local climate (?)*

*L. Blanc, J. Betbeder, Guido Briceño, TerrAmaz*

-   Indices to support management
-   Effect of deforestation on climate
-   Example for Temperature following @butt2023
-   Projections with future climates
-   DB Mato Grosso and regional climate changes?

### *Landscape trajectories and fires (?)*

*B. Bellon, J. Betbeder, L. Blanc*

-   Amazonian landscape trajectory in Brazil explored by B. Bellon
-   Could be linked to tropical moist forest fires using several products (e;g. MapBiomass, TMF, ...)

### *Forest landscape projections (?)*

*L. Blanc, J. Betbeder, I. Maréchaux, J. Chave*

-   developing and scaling up the TROLL simulator to simulate landscape
-   landscape forest modelling (LFM)
-   Similarly to LandClim (from ForClim) or ILand
-   Forest lanscape response to CC, management, and fires
-   Statistical approaches or other simulator could be used to

## Other

-   Biomass maps in Ivory Coast for S. Traore's PhD with C. Deforceville and B. Hérault
-   L. Baptiste manuscript on species growth in cacao agroforestry in Ivory Coast with B. Hérault
-   Local data dictionary for remote sensing and other data coupled with GitHub including data definition, download scripts, and eventually pre-processing
-   Particpation to Julien's PhD about climate effect on *Dicorynia guianensis* population genetics with climate expertise
-   Anne Baranger's manuscript on cocoa agroforestry with B. Hérault
-   Climate distribution of tree species in central africa with Charles Doumengue (building-up on the tool for downscaling?)
-   Tree species distribution in Sudano-Sahelian region since 1970 from presence-only occurrences and trying to identify climatic envelope evolutions. PhD co-supervised by Frédéric Mortier. Opportunity to join the CST.
-   TROLL formatting with P. Verley, T. Arsouze, and I. Maréchaux for future developments and/or student supervision.
